### ISSUE TITLE
Messed up local() output in font.css

### ISSUE THREAD

**Issue by joelpurra** [neverpanic/google-font-download#2]
When downloading the font `Cookie`, there is a second `local()` with what looks like a messed up value.

```css
@font-face {
	font-family: 'Cookie';
	font-style: normal;
	font-weight: normal;
	src:
		local('Cookie-Regular'),
		local('  src: local('Cookie-Regular'), url(http://fonts.gstatic.com/s/cookie/v7/Tvkve1y-JrkMx2S9u2OW1g.woff) format('woff');'),
		/* from http://fonts.gstatic.com/s/cookie/v7/AvlbhNBtDFTvYLPYKo-Lmg.eot */
		url('Cookie.eot?#iefix') format('embedded-opentype'),
		/* from http://fonts.gstatic.com/s/cookie/v7/Tvkve1y-JrkMx2S9u2OW1g.woff */
		url('Cookie.woff') format('woff'),
		/* from http://fonts.gstatic.com/l/font?kit=rlu5FEepl9muxv12LnwLGQ&skey=94aef82ff911a990#Cookie */
		url('Cookie.svg#Cookie') format('svg'),
		/* from http://fonts.gstatic.com/s/cookie/v7/pKcurCxn_Ato3MXK6jF2CA.ttf */
		url('Cookie.ttf') format('truetype');
}
```

This did not happen when downloading a few other fonts, either by themselves or together.
